default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 25
  username: postgres
  password: postgres

development:
  <<: *default
  database: conference_room_booking_development

test:
  <<: *default
  database: conference_room_booking_test

production:
  <<: *default
  database: 
  username: 
  password: <%= ENV['CONFERENCE_ROOM_BOOKING_DATABASE_PASSWORD'] %>
